Repository found-pleiade/dionysos-server, pull requests merged in 2022-08, with the labels that each got.

#70 Add cache
  go.mod
  go.sum
  routes/router.go
  variables/env.go
Labels: enhancement

#72 Fix cache connection and invalidation in PATCH and DELETE routes
  routes/router.go
Labels: enhancement

#75 Add recovery middleware
  routes/router.go
Labels: enhancement

#80 Remove password match for auth when in DEV mode
  routes/router.go
Labels: enhancement

#81 Correct nil pointer reference on OPTIONS call
  routes/router.go
Labels: bug

#85 76 create function to reset db before each test suite
  database/db.go
  routes/db.go
  routes/router.go
  tests/room_test.go
  tests/user_test.go
  utils/tests/tests.go
Labels: enhancement

#86 84 abort on authentication if user not found
  routes/router.go
  tests/middleware_test.go
  tests/user_test.go
Labels: bug

#71 User and room integration
  .env
  docker-compose.yaml
  go.mod
  go.sum
  models/room.go
  models/user.go
  routes/room.go
  routes/router.go
  tests/room_test.go
Labels: enhancement

#92 91 complexify id room
  go.mod
  go.sum
  models/room.go
  routes/room.go
  utils/uuid.go
Labels: enhancement

#96 Correct invalidateCache
  routes/router.go
Labels: bug

#98 feat(Healthz): Add a new route to test api liveness
  routes/healthz.go
  routes/router.go
Labels: enhancement

#101 99 use roomupdate struct during room creation
  routes/room.go
  routes/user.go
Labels: bug

#104 ci: Remove deploy operation
  .github/workflows/docker-push.yml
Labels: pipeline

#105 feat(hot reloading): Add hotreloading through air docker image
  .gitignore
  docker-compose.yaml
  docker/Dockerfile
Labels: enhancement

#100 93 change room users field so it is more comfortable for clients
  database/db.go
  models/room.go
  models/user.go
  routes/room.go
  routes/user.go
  tests/room_test.go
  tests/user_test.go
  utils/routes/conversion.go
  utils/routes/responses.go
  utils/tests/tests.go
Labels: tests, room

#106 57 add codecov badge to readme
  .env
  .github/workflows/tests.yml
  .gitignore
  README.md
  docker-compose_testing.yaml
  routes/middleware_test.go
  routes/room_test.go
  routes/user_test.go
  test.sh
Labels: pipeline, tests

#109 Add documentation to the project
  .github/workflows/super-linter.yml
  codecov.yaml
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  main.go
  models/room.go
  models/user.go
  routes/room.go
  routes/router.go
  routes/user.go
  routes/version.go
  utils/routes/responses.go
Labels: documentation

#111 107 add kick user route for a room
  README.md
  docker-compose_testing.yaml
  routes/room.go
  routes/router.go
  routes/tests/middleware_test.go
  routes/tests/room_test.go
  routes/tests/user_test.go
  test.sh
Labels: enhancement

#114 fix(Routes): Rename roomid to id in route parameter
  routes/router.go
Labels: bug
