Repository found-pleiade/dionysos-server, pull requests merged in 2022-07, with the labels that each got.

#35 Allow all origins cors
  main.go
Labels: bug

#36 32 fix access control allow origin 1
  main.go
Labels: bug

#38 Add Test Route step to CI
  .github/workflows/tests.yml
Labels: enhancement

#49 47 use super linter slim image
  .github/workflows/super-linter.yml
Labels: enhancement, pipeline

#51 Enforce / at the end of each route
  routes/router.go
  utils/tests/tests_rud.go
Labels: bug

#53 Remove cors middleware
  go.mod
  go.sum
  routes/router.go
Labels: bug

#54 Remove mandatory / at the end of routes
  routes/router.go
  tests/room_test.go
  tests/user_test.go
  utils/tests/tests_rud.go
Labels: enhancement, tests

#55 34 enforce best practises base path to route
  constants/constants.go
  routes/room.go
  routes/router.go
  routes/user.go
  tests/room_test.go
  tests/user_test.go
  utils/routes/responses.go
Labels: enhancement, tests

#63 56 add go report badge to readme
  README.md
  routes/db.go
Labels: documentation

#62 61 add env variable for base path
  database/db.go
  docker-compose.yaml
  docker-compose_testing.yaml
  routes/router.go
  tests/room_test.go
  tests/user_test.go
  utils/routes/responses.go
  variables/const.go
  variables/env.go
Labels: enhancement

#64 Delete base path in POST (create) response
  utils/routes/responses.go
Labels: bug

#66 65 implement authentication and authorization on certain routes
  models/user.go
  routes/room.go
  routes/router.go
  routes/user.go
  tests/middleware_test.go
  tests/room_test.go
  tests/user_test.go
  utils/routes/conversion.go
  utils/routes/responses.go
  utils/tests/tests.go
  utils/tests/tests_create.go
  utils/tests/tests_rud.go
  variables/const.go
Labels: enhancement, tests
